env:
  http:
    security:
      api-key:
        header: Authorization
        value: abc

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: